version: 2
updates:
# Update Gradle dependencies used in the project
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
# Update Github Actions tasks
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

